name: Build Check
on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
      - ".gitignore"
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - base/**
env:
  GO_VERSION: 1.21.3
  GOPATH: ${{ github.workspace }}/go
  WORKING_DIR: ${{ github.workspace }}/go/src/github.com/ethereum/go-ethereum
jobs:
  build:
    name: "Build geth on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        # Not enable for macos as there's a consistent failure:
        # --- FAIL: TestUPNP_DDWRT (2.20s)
        # ###[error]    natupnp_test.go:165: not discovered
        # must be sommething with Github Actions VM networking setup.
        # Event Ubuntu requires a workaround
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Setup Go ${{ env.GO_VERSION }}"
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Check out project files"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ${{ env.WORKING_DIR }}
      - name: "Apply workaround to fix networking in Linux"
        if: runner.os == 'Linux'
        run: |
          # https://github.com/actions/virtual-environments/issues/798
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
      - name: "Prepare environment"
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: "Build geth"
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          make geth
